# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Qiu\Desktop\mess\sudoku_project\python\mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 10, 1071, 641))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 180, 551, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.upload = QtWidgets.QPushButton(self.centralwidget)
        self.upload.setGeometry(QtCore.QRect(120, 390, 371, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.upload.setFont(font)
        self.upload.setObjectName("upload")
        self.puzzle = QtWidgets.QPushButton(self.centralwidget)
        self.puzzle.setGeometry(QtCore.QRect(580, 390, 361, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.puzzle.setFont(font)
        self.puzzle.setObjectName("puzzle")
        self.mode_back = QtWidgets.QPushButton(self.centralwidget)
        self.mode_back.setGeometry(QtCore.QRect(110, 40, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.mode_back.setFont(font)
        self.mode_back.setObjectName("mode_back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "选择模式"))
        self.upload.setText(_translate("MainWindow", "SAT求解"))
        self.puzzle.setText(_translate("MainWindow", "随机出题"))
        self.mode_back.setText(_translate("MainWindow", "返回"))
