# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Qiu\Desktop\mess\sudoku_project\python\rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RulesWindow(object):
    def setupUi(self, RulesWindow):
        RulesWindow.setObjectName("RulesWindow")
        RulesWindow.resize(1110, 659)
        self.centralwidget = QtWidgets.QWidget(RulesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 1111, 631))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, -20, 661, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 140, 1041, 451))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(28)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.rules_back = QtWidgets.QPushButton(self.centralwidget)
        self.rules_back.setGeometry(QtCore.QRect(60, 30, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.rules_back.setFont(font)
        self.rules_back.setObjectName("rules_back")
        RulesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RulesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        self.menubar.setObjectName("menubar")
        RulesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RulesWindow)
        self.statusbar.setObjectName("statusbar")
        RulesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RulesWindow)
        QtCore.QMetaObject.connectSlotsByName(RulesWindow)

    def retranslateUi(self, RulesWindow):
        _translate = QtCore.QCoreApplication.translate
        RulesWindow.setWindowTitle(_translate("RulesWindow", "MainWindow"))
        self.label.setText(_translate("RulesWindow", "游戏规则"))
        self.textEdit.setHtml(_translate("RulesWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bahnschrift SemiLight\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">游戏目标</span><span style=\" font-family:\'SimSun\'; font-size:16pt;\">：<br />对角线数独是一款基于经典数独规则的游戏，玩家需要在一个 9x9 的网格中填写数字，使每一行、每一列以及每个 3x3 宫内都包含 1 到 9 的数字，且每个数字不能重复。此外，对角线数独还要求两条对角线上（从左上角到右下角和从右上角到左下角）每个数字也不能重复。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">游戏模式</span><span style=\" font-family:\'SimSun\'; font-size:16pt;\">：</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'SimSun\'; font-size:16pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">SAT求解</span>：玩家可以上传一个由 CNF 格式文件表示的SAT问题。程序将解析题目，同时提供解题判定，判断是否存在解，并展示基础DPLL算法 和 优化后算法的求解对比。</li>\n"
"<li style=\" font-family:\'SimSun\'; font-size:16pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">随机出题</span>：系统将根据玩家选择的难度（不同的空白格数量）生成一个随机数独题目，玩家需要在限定时间内完成解题。</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">交互功能</span><span style=\" font-family:\'SimSun\'; font-size:16pt;\">：</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'SimSun\'; font-size:16pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">检查</span>：当玩家完成数独后，点击“检查”按钮，程序将标记出玩家的正确和错误答案，正确答案以绿色显示，错误答案以红色显示，数秒后所有颜色恢复为默认颜色。</li>\n"
"<li style=\" font-family:\'SimSun\'; font-size:16pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">偷看答案</span>：玩家可在游戏过程中点击“偷看答案”按钮，系统将展示完整的答案，答案在十秒后消失，恢复玩家当前输入的状态。</li>\n"
"<li style=\" font-family:\'SimSun\'; font-size:16pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">显示答案</span>：玩家在解题过程中可以选择显示完整答案，程序将记录偷看次数，并统计游戏时间。游戏结束时将显示玩家的偷看次数和总用时。</li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.rules_back.setText(_translate("RulesWindow", "返回"))
