# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Qiu\Desktop\杂\python\start.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 678)
        MainWindow.setMinimumSize(QtCore.QSize(824, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(824, 531))
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, -20, 1061, 671))
        self.listWidget.setObjectName("listWidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(130, -10, 901, 271))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.writer = QtWidgets.QLabel(self.centralwidget)
        self.writer.setGeometry(QtCore.QRect(670, 230, 431, 81))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(26)
        self.writer.setFont(font)
        self.writer.setObjectName("writer")
        self.game = QtWidgets.QPushButton(self.centralwidget)
        self.game.setGeometry(QtCore.QRect(120, 390, 371, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.game.setFont(font)
        self.game.setObjectName("game")
        self.rules = QtWidgets.QPushButton(self.centralwidget)
        self.rules.setGeometry(QtCore.QRect(560, 390, 371, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.rules.setFont(font)
        self.rules.setObjectName("rules")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "对角线数独游戏"))
        self.writer.setText(_translate("MainWindow", "设计者：邱月"))
        self.game.setText(_translate("MainWindow", "开始游戏"))
        self.rules.setText(_translate("MainWindow", "游戏规则"))
